@baseurl = http://localhost:3000/users
@idUser = 422e7f8c-24bc-4367-8406-4b6fc254afc7

### Users findAll() 
GET {{baseurl}}/

### Users findOne() 
GET {{baseurl}}/{{idUser}}

### Users Post() 
POST {{baseurl}} 
Content-Type: application/json

{
    "fullName": "Leonardo João Fleith", 
    "nickname": "Leo",
    "email": "kako@gmail.com", 
    "password": "senha123"
}

### Users Patch(idUser) 
PATCH {{baseurl}}/{{idUser}}
Content-Type: application/json

{
    "fullName": "Leonardo João Fleith att", 
    "nickname": "Leo att",
    "email": "novokako@gmail.com", 
    "password": "senha123 att"  
}

### Users Remove(idUser) 
DELETE {{baseurl}}/{{idUser}}