@baseurl = http://localhost:3000
@idUser = 0a491952-1f0f-4a6f-a8ef-5b5f339310eb

### Users findAll() 
GET {{baseurl}}/users

### Users findOne() 
GET {{baseurl}}/users/{{idUser}}

### Users Post() 
POST {{baseurl}}/users
Content-Type: application/json

{
    "fullName": "Leonardo João Fleith", 
    "nickname": "Leo",
    "email": "kako@gmail.com", 
    "password": "senha123"
}

### Users Patch(idUser) 
PATCH {{baseurl}}/users/{{idUser}}
Content-Type: application/json

{
    "fullName": "Leonardo João Fleith att", 

    "password": "senha123 att"  
}

### Users Remove(idUser) 
DELETE {{baseurl}}/users/{{idUser}}

####################################################################

@idCategory = f90fa45a-0775-4c36-a339-91683ef0124b

### Category findAll() 
GET {{baseurl}}/category

### Category findOne(idCategory) 
GET {{baseurl}}/category/{{idCategory}}

### Category Post() 
POST {{baseurl}}/category
Content-Type: application/json

{
    "name": "Login", 
    "description": "Logins de acesso"
}

### Category Patch(idCategory) 
PATCH {{baseurl}}/category/{{idCategory}}
Content-Type: application/json

{
    "name": "Login 2", 
    "description": "Logins de acesso 2"
}

### Category Remove(idCategory) 
DELETE {{baseurl}}/category/{{idCategory}}

####################################################################

@idLogin = b520a040-b19f-4082-bb2a-ca9c7a3f8a8d

### login findAll() 
GET {{baseurl}}/logins

### login findOne(idLogin) 
GET {{baseurl}}/logins/{{idLogin}}

### login Post() 
POST {{baseurl}}/logins
Content-Type: application/json

{
    "title": "Gmail do atendimento.ti", 
    "username": "atendimento.ti@unicesusc.edu.br", 
    "description": "Opcional", 
    "url": "gmail.com", 
    "password": "Cpd69@dmin", 
    "categoryId": "f90fa45a-0775-4c36-a339-91683ef0124b"

}



### login Patch(idLogin) 
PATCH {{baseurl}}/logins/{{idLogin}}
Content-Type: application/json

{
    "title": "Gmail do atendimento.ti atualizado", 
    "username": "atendimento.ti@unicesusc.edu.br atualizado", 
    "description": "Opcional atualizado", 
    "url": "gmail.com atualizado", 
    "password": "Cpd69@dmin atualizado",
}

### login Remove(idLogin) 
DELETE {{baseurl}}/logins/{{idLogin}}