@baseurl = http://localhost:3000
@idUser = 32cf333c-a0bd-450a-a9c4-4ee1e106cce6

### Users findAll() 
GET {{baseurl}}/users

### Users findOne() 
GET {{baseurl}}/users/{{idUser}}

### Users Post() 
POST {{baseurl}}/users
Content-Type: application/json

{
    "fullName": "Leonardo João Fleith", 
    "nickname": "Leo",
    "email": "apoio03.ti@unicesusc.edu.br", 
    "password": "senhaLeo"
}

### Users Patch(idUser) 
PATCH {{baseurl}}/users/{{idUser}}
Content-Type: application/json

{
    "fullName": "Leonardo João Fleith att", 
    "email": "fleithkako@gmail.com", 
    "nickname": "Leo", 
    "password": "senha123 att"  
}

### Users Remove(idUser) 
DELETE {{baseurl}}/users/{{idUser}}

####################################################################

@idCategory = c614ec1a-44ef-4d91-8e6d-cbbc59621808

### Category findAll() 
GET {{baseurl}}/category

### Category findOne(idCategory) 
GET {{baseurl}}/category/{{idCategory}}

### Category Post() 
POST {{baseurl}}/category
Content-Type: application/json

 {
    "name": "Documentação",
    "description": "Documentos técnicos e manuais do sistema"
  }

### Category Patch(idCategory) 
PATCH {{baseurl}}/category/{{idCategory}}
Content-Type: application/json

{
    "name": "Login 2", 
    "description": "Logins de acesso 2"
}

### Category Remove(idCategory) 
DELETE {{baseurl}}/category/{{idCategory}}

####################################################################

@idLogin = b520a040-b19f-4082-bb2a-ca9c7a3f8a8d

### login findAll() 
GET {{baseurl}}/logins

### login findOne(idLogin) 
GET {{baseurl}}/logins/{{idLogin}}

### login Post() 
POST {{baseurl}}/logins
Content-Type: application/json

{
    "title": "Gmail do atendimento.ti", 
    "username": "atendimento.ti@unicesusc.edu.br", 
    "url": "www.gmail.com", 
    "password": "Cpd69@dmin", 
    "categoryId": "c614ec1a-44ef-4d91-8e6d-cbbc59621808"

}



### login Patch(idLogin) 
PATCH {{baseurl}}/logins/{{idLogin}}
Content-Type: application/json

{
    "title": "Gmail do atendimento.ti atualizado", 
    "username": "atendimento.ti@unicesusc.edu.br atualizado", 
    "url": "gmail.com atualizado", 
    "password": "Cpd69@dmin atualizado"
}

### login Remove(idLogin) 
DELETE {{baseurl}}/logins/{{idLogin}}